<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

/** Writes docs/THIRD_PARTY_LICENSES.md from composer.lock (runtime packages) and the front-end packages that ship in the built assets. */
class BuildLicenses extends Command
{
    protected $signature = 'docs:licenses';

    protected $description = 'List the licences of bundled third-party packages';

    public function handle(): int
    {
        $lock = json_decode((string) file_get_contents(base_path('composer.lock')), true);
        $rows = collect($lock['packages'] ?? [])->map(fn ($p) => '| '.$p['name'].' | '.ltrim($p['version'], 'v').' | '.implode(', ', $p['license'] ?? ['unknown']).' |')->sort()->values();

        $front = [];
        $package = json_decode((string) file_get_contents(base_path('package.json')), true);

        foreach (array_keys($package['dependencies'] ?? []) as $name) {
            $meta = json_decode((string) @file_get_contents(base_path("node_modules/{$name}/package.json")), true);
            $front[] = '| '.$name.' | '.($meta['version'] ?? '?').' | '.($meta['license'] ?? 'see package').' |';
        }

        $md = "# Third-party licences\n\nThis product bundles open-source packages. Their licences allow commercial redistribution as part of an application; their copyright notices stay with their authors.\n"
            ."The list is generated by `php artisan docs:licenses` from `composer.lock` and `package.json`. Livewire brings Alpine.js (MIT).\n\n"
            ."## PHP packages (runtime)\n\n| Package | Version | Licence |\n| --- | --- | --- |\n".$rows->implode("\n")."\n\n"
            ."## Front-end packages (inside the compiled assets)\n\n| Package | Version | Licence |\n| --- | --- | --- |\n".implode("\n", $front)."\n\n"
            ."## Notes on specific licences\n\n"
            ."- **LGPL packages** (dompdf and its font/SVG libraries, smalot/pdfparser) are shipped unmodified in `vendor/` and can be replaced with another version through Composer, as the LGPL requires. Their source is available from their authors.\n"
            ."- **Dual-licensed packages** (nette/schema, nette/utils: BSD-3-Clause or GPL) are used under the BSD-3-Clause licence.\n\n"
            ."## Other\n\n- Dish illustrations and icons are original works made for this product (SVG), not stock photos.\n- Fonts: Inter and Bricolage Grotesque (SIL Open Font License 1.1), via Fontsource.\n";

        File::put(base_path('docs/THIRD_PARTY_LICENSES.md'), $md);
        $this->info('Wrote docs/THIRD_PARTY_LICENSES.md ('.($rows->count() + count($front)).' packages)');

        return self::SUCCESS;
    }
}
